name: Hello world

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Hello World!"

  A:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Job A
        run: echo "Este é o Job A (só corre depois do hello-world-job)"

  B:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Job B
        run: echo "Este é o Job B (só corre depois do hello-world-job)"
